/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.xemacscode.demo;

import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.xemacscode.demo.security.EncryptionService;

/**
 *
 * @author camil
 */
public class Registration extends javax.swing.JFrame {
    
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        this.setLocationRelativeTo(null); // Registration screen is shown in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Reg_FirstName = new javax.swing.JLabel();
        jLabel_Reg_LastName = new javax.swing.JLabel();
        jLabel_Reg_Username = new javax.swing.JLabel();
        jLabel_Reg_Email = new javax.swing.JLabel();
        jLabel_Reg_EmailConfirmation = new javax.swing.JLabel();
        jLabel_Reg_Password = new javax.swing.JLabel();
        jLabel_Reg_PasswordConfirmation = new javax.swing.JLabel();
        tfPasswordConfirm = new javax.swing.JPasswordField();
        tfPassword = new javax.swing.JPasswordField();
        tfMailConfirm = new javax.swing.JTextField();
        tfMail = new javax.swing.JTextField();
        tfUname = new javax.swing.JTextField();
        tfLname = new javax.swing.JTextField();
        tfFname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btn_Reg_Cancel = new javax.swing.JButton();
        jLabel_Reg_Login = new javax.swing.JLabel();
        jLabel_Registration = new javax.swing.JLabel();
        jLabel_HideScreen = new javax.swing.JLabel();
        jLabel_ExitScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(37, 116, 169));

        jPanel2.setBackground(new java.awt.Color(107, 184, 240));

        jLabel_Reg_FirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Reg_FirstName.setText("First Name:");

        jLabel_Reg_LastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Reg_LastName.setText("Last Name:");

        jLabel_Reg_Username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Reg_Username.setText("Username:");

        jLabel_Reg_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Reg_Email.setText("E-Mail:");

        jLabel_Reg_EmailConfirmation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Reg_EmailConfirmation.setText("E-Mail Confirmation:");

        jLabel_Reg_Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Reg_Password.setText("Password:");

        jLabel_Reg_PasswordConfirmation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Reg_PasswordConfirmation.setText("Password Confirmation:");

        tfPasswordConfirm.setBackground(new java.awt.Color(153, 153, 153));

        tfPassword.setBackground(new java.awt.Color(153, 153, 153));

        tfMailConfirm.setBackground(new java.awt.Color(153, 153, 153));

        tfMail.setBackground(new java.awt.Color(153, 153, 153));

        tfUname.setBackground(new java.awt.Color(153, 153, 153));

        tfLname.setBackground(new java.awt.Color(153, 153, 153));
        tfLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLnameActionPerformed(evt);
            }
        });

        tfFname.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(37, 116, 169));

        btnRegister.setBackground(new java.awt.Color(102, 255, 102));
        btnRegister.setText("Register");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btn_Reg_Cancel.setText("cancel");
        btn_Reg_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Reg_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Reg_CancelActionPerformed(evt);
            }
        });

        jLabel_Reg_Login.setText("Already have an account? click here");
        jLabel_Reg_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Reg_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Reg_LoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btn_Reg_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Reg_Login)
                .addGap(136, 136, 136))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btn_Reg_Cancel))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Reg_Login)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Reg_PasswordConfirmation)
                    .addComponent(jLabel_Reg_Password)
                    .addComponent(jLabel_Reg_EmailConfirmation)
                    .addComponent(jLabel_Reg_Email)
                    .addComponent(jLabel_Reg_Username)
                    .addComponent(jLabel_Reg_LastName)
                    .addComponent(jLabel_Reg_FirstName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPasswordConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(tfPassword)
                    .addComponent(tfMailConfirm)
                    .addComponent(tfMail)
                    .addComponent(tfUname)
                    .addComponent(tfLname)
                    .addComponent(tfFname))
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Reg_FirstName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reg_LastName)
                    .addComponent(tfLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reg_Username)
                    .addComponent(tfUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reg_Email)
                    .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reg_EmailConfirmation)
                    .addComponent(tfMailConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reg_Password)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reg_PasswordConfirmation)
                    .addComponent(tfPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_Registration.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Registration.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registration.setText("Registration");

        jLabel_HideScreen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_HideScreen.setText("-");
        jLabel_HideScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_HideScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_HideScreenMouseClicked(evt);
            }
        });

        jLabel_ExitScreen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_ExitScreen.setText("X");
        jLabel_ExitScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ExitScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitScreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Registration)
                .addGap(102, 102, 102)
                .addComponent(jLabel_HideScreen)
                .addGap(18, 18, 18)
                .addComponent(jLabel_ExitScreen)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_HideScreen)
                            .addComponent(jLabel_ExitScreen)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel_Registration)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLnameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String fname=tfFname.getText();
        String lname=tfLname.getText();
        String uname=tfUname.getText();
        String mail=tfMail.getText();
        String mailconfirm=tfMailConfirm.getText();
        String password=String.valueOf(tfPassword.getPassword());
        String passwordconfirm=String.valueOf(tfPasswordConfirm.getPassword());
        
        if(fname.isEmpty()||lname.isEmpty()||uname.isEmpty()||mail.isEmpty()||mailconfirm.isEmpty()||password.isEmpty()||passwordconfirm.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"One or more fields are empty.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!mail.equals(mailconfirm))
        {
            JOptionPane.showMessageDialog(this,"Check E-Mail Confirmation.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!password.equals(passwordconfirm))
        {
            JOptionPane.showMessageDialog(this,"Check Password Confirmation.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else try {
            if(checkUsername(uname))
            {
                JOptionPane.showMessageDialog(null,"Username already exist.","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if(checkEmail(mail))
            {
                JOptionPane.showMessageDialog(null,"Email already exist.","Error",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                userRegister(fname,lname,uname,mail,password);
            }
        } catch (SQLException | NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(this,"Something went wrong, please try again!","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btn_Reg_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Reg_CancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_Reg_CancelActionPerformed

    private void jLabel_HideScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HideScreenMouseClicked
        this.setState(JFrame.ICONIFIED);  // minimize the screen
    }//GEN-LAST:event_jLabel_HideScreenMouseClicked

    private void jLabel_ExitScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitScreenMouseClicked
        System.exit(0); //close the Login window
    }//GEN-LAST:event_jLabel_ExitScreenMouseClicked

    private void jLabel_Reg_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Reg_LoginMouseClicked
        dispose();
        Login l=new Login();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
    }//GEN-LAST:event_jLabel_Reg_LoginMouseClicked

    public boolean checkUsername(String uname) throws SQLException
    {
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist=false;
        String query="SELECT * FROM users WHERE username = ?";
        
        st=DBConnection.connectDB().prepareStatement(query);
        st.setString(1,uname);
        rs=st.executeQuery();
        if(rs.next())
        {
            username_exist=true;
            //JOptionPane.showMessageDialog(null,"Username already exist.","Error",JOptionPane.ERROR_MESSAGE);
        }
        return username_exist;
    }
    
    public boolean checkEmail(String mail) throws SQLException
    {
        PreparedStatement st;
        ResultSet rs;
        boolean email_exist=false;
        String query="SELECT * FROM users WHERE email = ?";
        
        st=DBConnection.connectDB().prepareStatement(query);
        st.setString(1,mail);
        rs=st.executeQuery();
        if(rs.next())
        {
            email_exist=true;
            //JOptionPane.showMessageDialog(null,"Username already exist.","Error",JOptionPane.ERROR_MESSAGE);
        }
        return email_exist;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btn_Reg_Cancel;
    private javax.swing.JLabel jLabel_ExitScreen;
    private javax.swing.JLabel jLabel_HideScreen;
    private javax.swing.JLabel jLabel_Reg_Email;
    private javax.swing.JLabel jLabel_Reg_EmailConfirmation;
    private javax.swing.JLabel jLabel_Reg_FirstName;
    private javax.swing.JLabel jLabel_Reg_LastName;
    private javax.swing.JLabel jLabel_Reg_Login;
    private javax.swing.JLabel jLabel_Reg_Password;
    private javax.swing.JLabel jLabel_Reg_PasswordConfirmation;
    private javax.swing.JLabel jLabel_Reg_Username;
    private javax.swing.JLabel jLabel_Registration;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfFname;
    private javax.swing.JTextField tfLname;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfMailConfirm;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPasswordField tfPasswordConfirm;
    private javax.swing.JTextField tfUname;
    // End of variables declaration//GEN-END:variables

    private void userRegister(String fname, String lname, String uname, String mail, String password) throws NoSuchAlgorithmException {
        Connection dbconn=DBConnection.connectDB();
        if(dbconn!=null)
        {
        try
        {
            PreparedStatement st=(PreparedStatement)dbconn.prepareStatement("INSERT INTO users (firstname,lastname,username,email,password) VALUE(?,?,?,?,?)");
            
            st.setString(1,fname);
            st.setString(2,lname);
            st.setString(3,uname);
            st.setString(4,mail);
            st.setString(5,EncryptionService.hashPassword(password));
            
            int res=st.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"New Account created.","Success",JOptionPane.INFORMATION_MESSAGE);
            
            dispose();
            Login loginwindow=new Login();
            loginwindow.setTitle("Login");
            loginwindow.setLocationRelativeTo(null);
            loginwindow.setVisible(true);
            
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
        else
        {
            System.out.println("The connection not available.");
        }
    }
}
